/**
 * Mock/demo Express server (server/index.js)
 * - In-memory sessions and messages (no DB)
 * - Endpoints:
 *   GET  /api/sessions
 *   POST /api/sessions
 *   GET  /api/sessions/:sessionId
 *   POST /api/sessions/:sessionId/message
 *
 * Simple, readable JS — basic/medium level.
 */

const express = require("express");
const cors = require("cors");
const { v4: uuid } = require("uuid");

const app = express();
const PORT = process.env.PORT || 4000;

app.use(cors());
app.use(express.json());

// In-memory store
// sessions: { [sessionId]: { sessionId, title, createdAt, updatedAt, messages: [] } }
const sessions = {};
let sessionCounter = 0;

function now() {
  return new Date().toISOString();
}

function generateTitleForSession(firstQuestion) {
  if (!firstQuestion) {
    sessionCounter += 1;
    return `New Chat ${sessionCounter}`;
  }
  // simple rule: use first 6 words or first 40 chars
  const trimmed = firstQuestion.trim();
  const words = trimmed.split(/\s+/).slice(0, 6).join(" ");
  return words.length > 40 ? words.slice(0, 40) + "..." : words;
}

// GET /api/sessions - return list of sessions
app.get("/api/sessions", (req, res) => {
  const list = Object.values(sessions).sort((a, b) =>
    b.updatedAt.localeCompare(a.updatedAt)
  );
  // Provide lightweight info for sidebar
  const result = list.map((s) => ({
    sessionId: s.sessionId,
    title: s.title,
    createdAt: s.createdAt,
    updatedAt: s.updatedAt,
    preview: s.messages.length
      ? (s.messages.find((m) => m.role === "user") || s.messages[0]).content
      : "",
  }));
  res.json(result);
});

// POST /api/sessions - create new session
app.post("/api/sessions", (req, res) => {
  const id = uuid();
  const createdAt = now();
  const title =
    req.body?.title || `New Chat ${Object.keys(sessions).length + 1}`;
  sessions[id] = {
    sessionId: id,
    title,
    createdAt,
    updatedAt: createdAt,
    messages: [],
  };
  res.status(201).json({ sessionId: id });
});

// GET /api/sessions/:sessionId - return full session history
app.get("/api/sessions/:sessionId", (req, res) => {
  const id = req.params.sessionId;
  const s = sessions[id];
  if (!s) return res.status(404).json({ error: "Session not found" });
  res.json(s);
});

// POST /api/sessions/:sessionId/message - post a question and get mock structured response
app.post("/api/sessions/:sessionId/message", (req, res) => {
  const id = req.params.sessionId;
  const s = sessions[id];
  if (!s) return res.status(404).json({ error: "Session not found" });

  const question = (req.body?.question || "").toString();
  const userMsg = {
    id: uuid(),
    role: "user",
    content: question,
    createdAt: now(),
  };
  s.messages.push(userMsg);

  // Maybe update title if it's the first user message
  if (!s.title || s.title.startsWith("New Chat")) {
    s.title = generateTitleForSession(question);
  }

  // Simple rule to choose table vs text:
  const low = question.toLowerCase();
  let assistantMsg;
  if (
    low.includes("table") ||
    low.includes("compare") ||
    low.includes("budget") ||
    low.includes("cost") ||
    low.includes("compare")
  ) {
    // Return a mock table response
    assistantMsg = {
      id: uuid(),
      role: "assistant",
      type: "table",
      description: "Below is a structured comparison based on your query.",
      table: {
        columns: ["Item", "Current", "Recommended", "Monthly Savings"],
        rows: [
          ["Streaming", "$50", "$20", "$30"],
          ["Phone", "$60", "$40", "$20"],
          ["Coffee", "$100", "$40", "$60"],
        ],
      },
      createdAt: now(),
    };
  } else {
    // Simple text response with an optional small table
    assistantMsg = {
      id: uuid(),
      role: "assistant",
      type: "text",
      content: `Mock reply: received your question "${question}". In a real app this would be generated by a model. Include keyword 'table', if you want table output`,
      createdAt: now(),
    };
  }

  s.messages.push(assistantMsg);
  s.updatedAt = now();

  // Return the assistant message (client will append)
  res.status(201).json(assistantMsg);
});

// Fallback simple health endpoint
app.get("/", (req, res) => {
  res.send("Mock chat server is running.");
});

app.listen(PORT, () => {
  console.log(`Mock server listening on http://localhost:${PORT}`);
});
